import { STORAGE_KEYS } from './config.js'
import { readJson, writeJson } from './storage.js'

// Product images from Unsplash
const IMAGES = {
  camisas: [
    'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=600&h=750&fit=crop',
  ],
  playeras: [
    'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&h=750&fit=crop',
  ],
  pantalones: [
    'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=750&fit=crop',
  ],
  sudaderas: [
    'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1578768079052-aa76e52ff62e?w=600&h=750&fit=crop',
  ],
  chamarras: [
    'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1559551409-dadc959f76b8?w=600&h=750&fit=crop',
  ],
  perfumes: [
    'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1541643600914-78b084683601?w=600&h=750&fit=crop',
  ],
  general: [
    'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=750&fit=crop',
    'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=750&fit=crop',
  ],
}

const SEED_PRODUCTS = [
  {
    id: 'p-oxford-01',
    name: 'Camisa Oxford',
    type: 'Camisas',
    price: 799,
    originalPrice: 999,
    colors: ['Negro', 'Blanco', 'Azul Marino'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Oferta',
    stock: 8,
    rating: 4.8,
    reviews: 24,
    images: IMAGES.camisas,
  },
  {
    id: 'p-poplin-01',
    name: 'Camisa Popelina Slim',
    type: 'Camisas',
    price: 849,
    originalPrice: null,
    colors: ['Blanco', 'Azul Cielo', 'Negro'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Nuevo',
    stock: 15,
    rating: 4.5,
    reviews: 12,
    images: IMAGES.camisas,
  },
  {
    id: 'p-tee-01',
    name: 'Playera Básica Premium',
    type: 'Playeras',
    price: 299,
    originalPrice: null,
    colors: ['Negro', 'Blanco', 'Gris', 'Verde Olivo'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    badge: 'Popular',
    stock: 50,
    rating: 4.9,
    reviews: 89,
    images: IMAGES.playeras,
  },
  {
    id: 'p-tee-02',
    name: 'Playera Oversize',
    type: 'Playeras',
    price: 349,
    originalPrice: 449,
    colors: ['Negro', 'Blanco', 'Arena'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Oferta',
    stock: 3,
    rating: 4.6,
    reviews: 31,
    images: IMAGES.playeras,
  },
  {
    id: 'p-polo-01',
    name: 'Polo Piqué',
    type: 'Polos',
    price: 549,
    originalPrice: null,
    colors: ['Negro', 'Azul Marino', 'Blanco'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: null,
    stock: 20,
    rating: 4.7,
    reviews: 18,
    images: IMAGES.general,
  },
  {
    id: 'p-jean-01',
    name: 'Jeans Slim',
    type: 'Pantalones',
    price: 1099,
    originalPrice: 1299,
    colors: ['Azul', 'Negro'],
    sizes: ['30', '32', '34', '36', '38'],
    badge: 'Oferta',
    stock: 12,
    rating: 4.8,
    reviews: 45,
    images: IMAGES.pantalones,
  },
  {
    id: 'p-jean-02',
    name: 'Jeans Regular',
    type: 'Pantalones',
    price: 999,
    originalPrice: null,
    colors: ['Azul Oscuro', 'Negro'],
    sizes: ['30', '32', '34', '36', '38'],
    badge: null,
    stock: 25,
    rating: 4.4,
    reviews: 22,
    images: IMAGES.pantalones,
  },
  {
    id: 'p-chino-01',
    name: 'Pantalón Chino',
    type: 'Pantalones',
    price: 949,
    originalPrice: null,
    colors: ['Negro', 'Beige', 'Verde Olivo'],
    sizes: ['30', '32', '34', '36', '38'],
    badge: 'Nuevo',
    stock: 18,
    rating: 4.6,
    reviews: 15,
    images: IMAGES.pantalones,
  },
  {
    id: 'p-bermuda-01',
    name: 'Short Chino',
    type: 'Shorts',
    price: 699,
    originalPrice: null,
    colors: ['Negro', 'Beige'],
    sizes: ['30', '32', '34', '36'],
    badge: null,
    stock: 10,
    rating: 4.3,
    reviews: 8,
    images: IMAGES.general,
  },
  {
    id: 'p-hoodie-01',
    name: 'Sudadera Hoodie Minimal',
    type: 'Sudaderas',
    price: 899,
    originalPrice: 1099,
    colors: ['Negro', 'Gris'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Popular',
    stock: 6,
    rating: 4.9,
    reviews: 67,
    images: IMAGES.sudaderas,
  },
  {
    id: 'p-crewneck-01',
    name: 'Sudadera Crewneck',
    type: 'Sudaderas',
    price: 849,
    originalPrice: null,
    colors: ['Negro', 'Gris', 'Azul Marino'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: null,
    stock: 14,
    rating: 4.5,
    reviews: 19,
    images: IMAGES.sudaderas,
  },
  {
    id: 'p-sweater-01',
    name: 'Suéter Tejido Fino',
    type: 'Suéteres',
    price: 899,
    originalPrice: null,
    colors: ['Negro', 'Gris', 'Bordó'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Nuevo',
    stock: 9,
    rating: 4.7,
    reviews: 11,
    images: IMAGES.general,
  },
  {
    id: 'p-jacket-01',
    name: 'Chamarra Urban',
    type: 'Chamarras',
    price: 1699,
    originalPrice: null,
    colors: ['Negro'],
    sizes: ['M', 'L', 'XL'],
    badge: null,
    stock: 2,
    rating: 4.8,
    reviews: 28,
    images: IMAGES.chamarras,
  },
  {
    id: 'p-jacket-02',
    name: 'Chamarra Bomber',
    type: 'Chamarras',
    price: 1899,
    originalPrice: 2299,
    colors: ['Negro', 'Verde Olivo'],
    sizes: ['S', 'M', 'L', 'XL'],
    badge: 'Oferta',
    stock: 4,
    rating: 4.9,
    reviews: 52,
    images: IMAGES.chamarras,
  },
  {
    id: 'p-coat-01',
    name: 'Abrigo de Paño',
    type: 'Abrigos',
    price: 2999,
    originalPrice: null,
    colors: ['Negro', 'Gris'],
    sizes: ['M', 'L', 'XL'],
    badge: 'Premium',
    stock: 5,
    rating: 5.0,
    reviews: 14,
    images: IMAGES.chamarras,
  },
  // Perfumes
  {
    id: 'p-perfume-01',
    name: 'Perfume Intense Noir',
    type: 'Perfumes',
    price: 1299,
    originalPrice: 1599,
    colors: ['100ml', '50ml'],
    sizes: ['100ml', '50ml'],
    badge: 'Oferta',
    stock: 12,
    rating: 4.9,
    reviews: 45,
    images: IMAGES.perfumes,
  },
  {
    id: 'p-perfume-02',
    name: 'Perfume Fresh Ocean',
    type: 'Perfumes',
    price: 999,
    originalPrice: null,
    colors: ['100ml', '50ml'],
    sizes: ['100ml', '50ml'],
    badge: 'Nuevo',
    stock: 20,
    rating: 4.7,
    reviews: 32,
    images: IMAGES.perfumes,
  },
  {
    id: 'p-perfume-03',
    name: 'Perfume Classic Wood',
    type: 'Perfumes',
    price: 1499,
    originalPrice: null,
    colors: ['100ml'],
    sizes: ['100ml'],
    badge: 'Premium',
    stock: 8,
    rating: 5.0,
    reviews: 28,
    images: IMAGES.perfumes,
  },
  {
    id: 'p-perfume-04',
    name: 'Perfume Sport Energy',
    type: 'Perfumes',
    price: 799,
    originalPrice: 999,
    colors: ['100ml', '50ml'],
    sizes: ['100ml', '50ml'],
    badge: 'Popular',
    stock: 25,
    rating: 4.8,
    reviews: 67,
    images: IMAGES.perfumes,
  },
]

const SEED_VERSION = 3 // Increment this to force re-seed

export function ensureSeedData() {
  const storedVersion = localStorage.getItem('gl_seed_version')
  const existing = readJson(STORAGE_KEYS.products, null)
  
  // Force re-seed if version changed or no products
  if (storedVersion !== String(SEED_VERSION) || !Array.isArray(existing) || existing.length === 0) {
    writeJson(STORAGE_KEYS.products, SEED_PRODUCTS)
    localStorage.setItem('gl_seed_version', String(SEED_VERSION))
  }
}
